[project]
name = "comfyui-ck-telemetry"
version = "1.0.4"
description = "ComfyUI diagnostic utility for ROCm/HIP Comfy Kitchen builds: It reports either detailed or summarized Comfy Kitchen kernel dispatch info, and other insightful aspects, such as hardware/stack performance. The custom node has the ability to persistively store the reports, just by simply being wired anywhere within functional ComfyUI workflows (which includes placement even after any 'Save' Image/Video/Audio/Latent/etc node that has an output to hook into). Project also features flag/env var option to display summary or detailed reports via terminal, without involvement of the custom node. Intentionally very lightweight, utilizing just psutil, WDDM, and ultimately optimized and intended for AMD GPU users on Windows."
readme = "README.md"
license = { text = "MIT" }
dependencies = ["psutil>=5.9.0"]

[project.urls]
Repository = "https://github.com/Elsewhere101/ComfyUI-CK-Telemetry"

[tool.comfy]
PublisherId = "elsewhere101"
DisplayName = "CK-Telemetry"
Icon = "https://i.ibb.co/Rprv694Z/ckt1.png"
